version: "3.9"

services:
  godo:
    image: godo:v1         # 或者使用 build 构建（见下方）
    container_name: godo
    restart: always
    network_mode: "host"           # 使用主机网络
    volumes:
      - ./config.yaml:/config/config.yaml   # ← 映射单个文件
      - ./uploads:/app/uploads                 # ← 映射目录
      - ./logs:/app/logs                 # ← 映射目录
    environment:
      TZ: "Asia/Shanghai"
