server:
  host: 0.0.0.0
  port: 8080

db:
  addr: "root:12345678@tcp(localhost:3306)/GoDo?charset=utf8mb4&parseTime=True&loc=Local"

schedule:
  with_seconds: true
  work_dir: "./uploads"

log:
  level: "info"
  format: "console"
  path: "./logs"
  file_name: "app.log"
  max_size: 100
  max_age: 7
  compress: true
  stdout: true